### ISSUE TITLE
Incompatibility with Composer 1

### ISSUE THREAD

**Issue by sudofox** [VincentLanglet/Twig-CS-Fixer#121]
It seems that this library, while it does install fine on

```
Composer version 1.10.26 2022-04-13 16:39:56
```

requires Composer\InstalledVersions which is a Composer 2 thing, making it incompatible.

Might want to either

- find an alternative to where that's used, to increase compatibility (what I'd prefer)
- update package metadata to enforce proper compatibility checks on installation

**Comment by sudofox** [comment]
(i solved my personal issue with `yum --enablerepo=remi update composer` to get composer 2 but it's still prob worth doing. i think you can target composer api or something?)

**Comment by VincentLanglet** [comment]
`Composer\InstalledVersions` is used to determine the installed version in order to reset the cache when the version change.

Compose v2 is 3 years old and Composer v1 is deprecated (https://blog.packagist.com/deprecating-composer-1-support/) so I dont think it's worth working on such compatibility.
