### ISSUE TITLE
Code Indentation

### ISSUE THREAD

**Issue by lgeorgiev** [VincentLanglet/Twig-CS-Fixer#309]
Hello,
the Twig documentation has the following example:

_Indent your code inside tags (use the same indentation as the one used for the target language of the rendered template):_
```twig
{% block foo %}
    {% if true %}
        true
    {% endif %}
{% endblock %}
```
Is there a rule by which I can achieve such formatting?

**Comment by VincentLanglet** [comment]
> Is there a rule by which I can achieve such formatting?

No, there is none. Because it's too complicated and require to much logic:
- It would certainly require to indent html too
- It would require to understand the block

As an example
```
{% block foo %}
{% if true %}
     true
{% endif %}
{% endblock %}
```
need to be fixed, but
```
{% set foo = 1 %}
{% if true %}
     true
{% endif %}
{% set bar = 2 %}
```
doesn't require a fixed, but is tokenized in a similar way.

You can find more explanation in related issues like
- https://github.com/VincentLanglet/Twig-CS-Fixer/issues/243
- https://github.com/VincentLanglet/Twig-CS-Fixer/issues/47

**Comment by vinceAmstoutz** [comment]
I'm curious and motivated to try to work on it @VincentLanglet if you want

**Comment by VincentLanglet** [comment]
> I'm curious and motivated to try to work on it @VincentLanglet if you want

Nice, I can answer to any question 
- here
- in a github discussions
- or on slack (symfony-devs.slack.com)
